build:
    environment:
        python: '3.5.0'
    dependencies:
        before:
            - 'sudo apt-get install -y mercurial'
            - 'pip install -r tests/requirements/python3.txt'
        override:
                - 'python setup.py develop'
    tests:
        override:
            -
                command: 'fab test:coverage'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*tests*'
        - 'fabfile.py'
        - 'docs/*'
        - '*migrations*'
        - '*south_migrations*'
